language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: 139.59.124.114
install: npm install
before_install:
- openssl aes-256-cbc -K $encrypted_86e69b11877e_key -iv $encrypted_86e69b11877e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
